[astro-dev]

## image type
#image=ghcr.io/linuxcontainers/alpine:latest
#image=ghcr.io/linuxcontainers/debian:latest
#image=ghcr.io/linuxcontainers/debian-slim:latest
image=registry.fedoraproject.org/fedora-toolbox:latest

## packages to install
additional_packages="git make fish btop zip unzip npm"

## distrobox config options
pull=true
init=false
root=false
nvidia=false
replace=false
exported_bins_path="$HOME/.local/bin $HOME/bin"

## other distrobox options
#home=$HOME/dbxAlpine
#export="EDITOR=vim"
#init_hooks="rm /usr/bin/vi; ln -s /usr/bin/vim /usr/bin/vi"
#exported_bins="/usr/bin/git"
#additional_flags="--env PIPX_HOME=venvs/lib/python*/site-packages/requiried"
#exported_bins="/usr/bin/pipx"

