---
services:
  static-web-server:
    image: ghcr.io/static-web-server/static-web-server:2-alpine
    environment:
      # static-web-server config
      - SERVER_PORT=8080
      - SERVER_ROOT=/public
      - SERVER_LOG_LEVEL=info
    container_name: ${SITE_NAME}
    restart: unless-stopped
    volumes:
      - ./html:/public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${SITE_NAME}.tls=true"
      - "traefik.http.routers.${SITE_NAME}.tls.certresolver=le"
      - "traefik.http.routers.${SITE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SITE_NAME}.rule=Host(`${SITE_FQDN}`)"
      - "traefik.http.services.${SITE_NAME}.loadbalancer.server.port=${SITE_PORT}"
    networks:
      - proxy

networks:
  proxy:
    external: true
